# docker run --name pet-adoption-api -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=petadoptionapi -p 5432:5432 bitnami/postgresql

version: '3'

services:
  pet-adoption-api:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=petadoptionapi
